#ifndef PREFS_H
#define PREFS_H

#define JOYSTICK_PORT 0
#define JOYSTICKTWO_PORT 1

#define FL_PORT 1
#define FR_PORT 3
#define BL_PORT 0
#define BR_PORT 2
#define RIGHTLIFTER_PORT 1
#define LEFTLIFTER_PORT 0
#define TONGUE_PORT 2

#define DETECTOR_IP "10.23.58.11"
#define DETECTOR_LED_PORT 0

#define COMPRESSOR_SWITCH_PORT 5
#define COMPRESSOR_RELAY_PORT 1

#define GRIPPER_EXTEND_SOLENOID 1
#define GRIPPER_RETRACT_SOLENOID 0
#define TONGUE_EXTEND_PORT 3
#define TONGUE_RETRACT_PORT 2

#define LIFT_ENCODER_PORT_1 1
#define LIFT_ENCODER_PORT_2 2

#define LIFTER_SWITCH_PORT 0
#define TONGUE_SWITCH_PORT 3
#define TONGUE_BACK_SWITCH_PORT 9

#define LIGHT_RING_CONTROLLER_ADDRESS 0x4
#define JAKE_GYRO_ADDRESS 0x68

#define DRIVE_ENCODER_PORT_1 6
#define DRIVE_ENCODER_PORT_2 7

#define ENCODER_CONSTANT 90
#define MECANUM_CIRCUMFERENCE 12.56637
#define THREE_FEET 81
#define SIX_FEET 162

#endif
