#ifndef PREFS_H
#define PREFS_H

#define GYRO_PORT 1

#define JOYSTICK_PORT 0

#define FL_PORT 0
#define FR_PORT 1
#define BL_PORT 2
#define BR_PORT 3
#define RIGHTLIFTER_PORT 3
#define LEFTLIFTER_PORT 1
#define TONGUE_PORT 6

#define DETECTOR_IP "10.23.58.11"
#define DETECTOR_LED_PORT 0

#define COMPRESSOR_SWITCH_PORT 5
#define COMPRESSOR_RELAY_PORT 1

#define RGRIPPER_EXTEND_SOLENOID 1
#define RGRIPPER_RETRACT_SOLENOID 0
#define LGRIPPER_EXTEND_SOLENOID 2
#define LGRIPPER_RETRACT_SOLENOID 3

#define LIFT_ENCODER_PORT_1 1
#define LIFT_ENCODER_PORT_2 2

#endif
