#ifndef PREFS_H
#define PREFS_H

#define GYRO_PORT 1

#define JOYSTICK_PORT 0

#define FL_PORT 0
#define FR_PORT 1
#define BL_PORT 2
#define BR_PORT 3
#define RIGHTLIFTER_PORT 3
#define LEFTLIFTER_PORT 1
#define TONGUE_PORT 6

#define DETECTOR_IP "10.23.58.11"
#define DETECTOR_LED_PORT 0

#define COMPRESSOR_SWITCH_PORT 5
#define COMPRESSOR_RELAY_PORT 1

#define PISTON_EXTEND_SOLENOID 0
#define PISTON_RETRACT_SOLENOID 1

#endif
